# Generated by Django 5.1.4 on 2024-12-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchmate', '0003_review_review_user_alter_review_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='avg_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='number_rating',
            field=models.IntegerField(default=0),
        ),
    ]
